config/routes.rb
Rails.application.routes.draw do
  resources :emails
  resources :epostcards
  get 'deliver', to: 'emails#deliver', as: :deliver_epostcard
  resources :pages
  resources :lodgings
  devise_for :users
  get 'home/index'
  root to: "home#index"
  resources :users

end

app/models/user.rb
class User < ApplicationRecord
  devise :invitable, :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
  has_many :lodgings
  accepts_nested_attributes_for :lodgings
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
    @lodgings = @user.lodgings
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      # params.fetch(:user, {})
      # params.require(:user).permit(:name, lodgings_attributes: [:id, :name, :_destroy])
      params.require(:user).permit(:name, :lodging_ids, lodging_ids: [])
      
    end
end

app/helpers/users_helper.rb
module UsersHelper
  
  def user_status(user)
    if current_user == user || user.invitation_accepted?
      content_tag(:span, 'Active', class: 'checkmark')
    else
      'Invite Pending'
    end
  end
end

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :email
    %br/
    = f.email_field :email
  

  .actions
    = f.submit 'Save', class: "btn btn-success"

    = link_to 'Back', users_path, class: "btn btn-info"

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

app/views/users/index.html.haml
%h1 Listing users

%table.table.table-bordered.table-striped
  %thead
    %tr
      %th ID
      %th e-mail
      %th Status
      %th Lodging
      %th{:colspan => 3}

  %tbody
    - @users.each do |user|
      %tr
        %td= user.id
        %td= user.email
        %td= user_status(user)
        %td= user.lodgings.first ?  user.lodgings.first.company_name : ''
        %td= link_to icon('eye'), user, title: 'view this user'
        %td= link_to icon('pencil'), edit_user_path(user), title: 'edit this user'
        %td= link_to icon('trash'), user, title: 'delete this user',  :method => :delete, :data => { :confirm => 'Are you sure?' }

.actions
  = link_to 'Invite a New User', new_user_invitation_path, class: "btn btn-warning"

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
%p#notice= notice

.row
  .col-md-8
    %h1 User:  #{@user.email}
  .col-md-4.mt-3
    %p status: #{user_status(@user)}

.row.col-md-4
  %h3 Lodgings for this user:
.row.col-md-8.offset-md-1.mt-3
  -case @lodgings.count
  - when 0
    This user does not have an associated lodging
  - else
    - @lodgings.each do |lodging|
      = link_to lodging.company_name, lodging_path(lodging.id)
      %br

.row.col-8.mt-5
  %b change lodging for this user
.row.col-8
  %p select a lodging below:
  = form_for @user do |f|
    - if @user.errors.any?
      #error_explanation
        %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
        %ul
          - @user.errors.full_messages.each do |msg|
            %li= msg
    .field
      %br/
      = f.collection_select(:lodging_ids, Lodging.all, :id, :company_name, {:prompt => "select lodging"} )
    
  
    .actions
      = f.submit 'Change Logding', class: "btn btn-success"



.actions.mt-5
  = link_to 'Edit this user', edit_user_path(@user), class: "btn btn-warning"
  = link_to 'Back', users_path, class: "btn btn-info"