config/routes.rb
Rails.application.routes.draw do
  resources :emails
  resources :epostcards
  get 'deliver', to: 'emails#deliver', as: :deliver_epostcard
  resources :pages
  resources :lodgings
  devise_for :users
  get 'home/index'
  root to: "home#index"
  resources :users

end

app/models/lodging.rb
class Lodging < ApplicationRecord
  belongs_to :user, optional: true
  has_many :pages
  has_many :emails

  def self.search(term)
    if term
      where('company_name LIKE ?', "%#{term}%")
    else
      order('company_name ASC')
    end
  end

  def display_address
    [address_line_one, address_line_two, city, state].join(' ')
  end

end

app/controllers/lodgings_controller.rb
class LodgingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_lodging, only: [:show, :edit, :update, :destroy]

  def index
    @lodgings = Lodging.search(params[:term])
    # @lodgings = Lodging.all
  end

  def show
    @epostcard_page = @lodging.pages.where(page_type: "e-postcard").first
  end

  def new
    @lodging = Lodging.new
  end

  def edit
  end

  def create
    @lodging = Lodging.new(lodging_params)

    respond_to do |format|
      if @lodging.save
        format.html { redirect_to @lodging, notice: 'Lodging was successfully created.' }
        format.json { render :show, status: :created, location: @lodging }
      else
        format.html { render :new }
        format.json { render json: @lodging.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @lodging.update(lodging_params)
        format.html { redirect_to @lodging, notice: 'Lodging was successfully updated.' }
        format.json { render :show, status: :ok, location: @lodging }
      else
        format.html { render :edit }
        format.json { render json: @lodging.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @lodging.destroy
    respond_to do |format|
      format.html { redirect_to lodgings_url, notice: 'Lodging was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lodging
      @lodging = Lodging.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lodging_params
      params.require(:lodging).permit(:destination_ref, :region_ref, :company_name, :address_line_one, :address_line_two, :city, :state, :zip, :phone, :reservation, :fax, :url, :contact, :season, :email, :details, :mask2id_ref, :expires_at, :paid_at, :customer_status_notes, :user_id)
    end
end

app/helpers/lodgings_helper.rb
module LodgingsHelper
end

app/views/lodgings/_form.html.haml
= form_for @lodging do |f|
  - if @lodging.errors.any?
    #error_explanation
      %h2= "#{pluralize(@lodging.errors.count, "error")} prohibited this lodging from being saved:"
      %ul
        - @lodging.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :destination_ref
    = f.text_field :destination_ref
  .field
    = f.label :region_ref
    = f.text_field :region_ref
  .field
    = f.label :company_name
    = f.text_field :company_name
  .field
    = f.label :address_line_one
    = f.text_field :address_line_one
  .field
    = f.label :address_line_two
    = f.text_field :address_line_two
  .field
    = f.label :city
    = f.text_field :city
  .field
    = f.label :state
    = f.text_field :state
  .field
    = f.label :zip
    = f.text_field :zip
  .field
    = f.label :phone
    = f.text_field :phone
  .field
    = f.label :reservation
    = f.text_field :reservation
  .field
    = f.label :fax
    = f.text_field :fax
  .field
    = f.label :url
    = f.text_field :url
  .field
    = f.label :contact
    = f.text_field :contact
  .field
    = f.label :season
    = f.text_field :season
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :details
    = f.text_field :details
  .field
    = f.label :mask2id_ref
    = f.text_field :mask2id_ref
  .field
    = f.label :expires_at
    = f.datetime_select :expires_at
  .field
    = f.label :paid_at
    = f.datetime_select :paid_at
  .field
    = f.label :customer_status_notes
    = f.text_field :customer_status_notes
  .field
    = f.label :user
    = f.text_field :user
  .actions
    = f.submit 'Save'

app/views/lodgings/edit.html.haml
%h1 Editing lodging

= render 'form'

= link_to 'Show', @lodging
\|
= link_to 'Back', lodgings_path

app/views/lodgings/index.html.haml
%h1 Listing lodgings
%h2 #{@lodgings.count} total

%table.table.table-bordered.table-striped
  %thead
    %tr
      %th Company name
      %th City
      %th State
      %th Url
      %th Contact
      %th Email
      %th
      %th
      %th

  %tbody
    - @lodgings.each do |lodging|
      %tr
        %td= lodging.company_name
        %td= lodging.city
        %td= lodging.state
        %td= truncate(lodging.url, length: 37)
        %td= truncate(lodging.contact, length: 10)
        %td= truncate(lodging.email, length: 30)
        %td= link_to 'Show', lodging
        %td= link_to 'Edit', edit_lodging_path(lodging)
        %td= link_to 'Destroy', lodging, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Lodging', new_lodging_path

app/views/lodgings/new.html.haml
%h1 New lodging

= render 'form'

= link_to 'Back', lodgings_path

app/views/lodgings/show.html.haml
%p#notice= notice

%h1= @lodging.company_name

.row.col-lg-9.mt-3
  %table.table.table-striped.table-bordered.table-responsive
    %tr.table-success
      %th Lodging Name
      %th Region
      %th{colspan: 5} Address
    %tr
      %td= @lodging.company_name
      %td= @lodging.region_ref
      %td= @lodging.address_line_one
      %td= @lodging.address_line_two
      %td= @lodging.city
      %td= @lodging.state
      %td= @lodging.zip

.row.col-lg-10.mt-9
  %table.table.table-striped.table-bordered.table-responsive
    %tr.table-success
      %th Phone:
      %th Reservation:
      %th Fax:
      %th Url:
      %th Contact:
      %th Season:
      %th Email:
      %th Details:
    %tr
      %td= @lodging.phone
      %td= @lodging.reservation
      %td= @lodging.fax
      %td= @lodging.url
      %td= @lodging.contact
      %td= @lodging.season
      %td= @lodging.email
      %td= @lodging.details


.actions.mt-2
  = link_to 'Edit lodging info', edit_lodging_path(@lodging), class: "btn btn-warning"
  = link_to 'Back', lodgings_path, class: "btn btn-info"


.row.mt-5
  %h2 Lodging Services

.row.col-lg-10.mt-9
  %table.table.table-striped.table-bordered.table-responsive
    %tr.table-info
      %th Service
      %th Active ?
      %th Subscription valid until
      %th
    %tr
      %td e-postcard
      %td Yes
      %td= distance_of_time_in_words(Time.now, 1.years.from_now ) + " from now"
      %td
        -if @epostcard_page.present?
          = link_to 'view service', page_path(@epostcard_page.id), class: "btn btn-success"
          = link_to 'edit service', edit_page_path(@epostcard_page.id), class: "btn btn-warning"
        -else
          = link_to 'enable service', new_page_path(lodging_id: @lodging.id), class: "btn btn-danger"

    %tr
      %td Nearby Navigator
      %td No
      %td expired
      %td= link_to 'enable service', page_path(2), class: "btn btn-danger"